package interfazGrafica;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import lvlup.shop.JFondo;
import lvlup.shop.Juego;
import repositorios.*;

/**
 *
 * @author Marcos&&German
 */
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 * Esta es la clase principal que se encarga de crear y modelar a la tienda.
 *
 * @author marco
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Este contructor se encarga de iniciar todos los componentes y mostrar o
     * abrir la tienda
     */
    public VentanaPrincipal() {
        initComponents();
        cargarEtiquetas(panelCentralJuegos);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jpanelFondo = new JFondo("fondoFinal.png");
        panelMenuLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnJuegos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnDevolverJuegos = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        btnPoliticas = new javax.swing.JButton();
        panelSuperiorBuscar = new javax.swing.JPanel();
        labelAddCarri = new javax.swing.JLabel();
        contadorJuegos = new javax.swing.JLabel();
        textBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelCentralJuegos = new javax.swing.JPanel();
        btnCarritoTop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuAddJuegos = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuAddCliente = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LvlUp-Shop");
        setResizable(false);

        jpanelFondo.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jpanelFondo.setName(""); // NOI18N
        jpanelFondo.setOpaque(false);

        panelMenuLateral.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("LvlUp-Shop");
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(false);

        btnJuegos.setBackground(new java.awt.Color(255, 255, 255));
        btnJuegos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnJuegos.setText("Juegos");
        btnJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegosActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnDevolverJuegos.setBackground(new java.awt.Color(255, 255, 255));
        btnDevolverJuegos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDevolverJuegos.setText("Devolver Juegos");
        btnDevolverJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverJuegosActionPerformed(evt);
            }
        });

        btnInformes.setBackground(new java.awt.Color(255, 255, 255));
        btnInformes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnInformes.setText("Informes");
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });

        btnPoliticas.setBackground(new java.awt.Color(255, 255, 255));
        btnPoliticas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPoliticas.setText("Politicas");
        btnPoliticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLateralLayout = new javax.swing.GroupLayout(panelMenuLateral);
        panelMenuLateral.setLayout(panelMenuLateralLayout);
        panelMenuLateralLayout.setHorizontalGroup(
            panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLateralLayout.createSequentialGroup()
                .addGroup(panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLateralLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLateralLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLateralLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLateralLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnDevolverJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLateralLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLateralLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnPoliticas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelMenuLateralLayout.setVerticalGroup(
            panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDevolverJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPoliticas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(591, Short.MAX_VALUE))
        );

        panelSuperiorBuscar.setOpaque(false);

        labelAddCarri.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAddCarri.setForeground(new java.awt.Color(255, 204, 204));
        labelAddCarri.setText("Juegos Añadidos");

        contadorJuegos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contadorJuegos.setForeground(new java.awt.Color(255, 204, 204));
        contadorJuegos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorJuegos.setText("0");

        textBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textBuscar.setText("Buscar Juegos...");
        textBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBuscarMouseClicked(evt);
            }
        });
        textBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new Dimension(cantJuegos*280,600));

        panelCentralJuegos.setBackground(new java.awt.Color(0, 0, 0));
        panelCentralJuegos.setOpaque(false);
        panelCentralJuegos.setPreferredSize(new Dimension(cantJuegos*280,600));

        javax.swing.GroupLayout panelCentralJuegosLayout = new javax.swing.GroupLayout(panelCentralJuegos);
        panelCentralJuegos.setLayout(panelCentralJuegosLayout);
        panelCentralJuegosLayout.setHorizontalGroup(
            panelCentralJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCentralJuegosLayout.setVerticalGroup(
            panelCentralJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelCentralJuegos);

        btnCarritoTop.setIcon(new ImageIcon("./src/images/carritoTop.png"));
        btnCarritoTop.setOpaque(false);
        btnCarritoTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoTopActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Carrito->");

        javax.swing.GroupLayout jpanelFondoLayout = new javax.swing.GroupLayout(jpanelFondo);
        jpanelFondo.setLayout(jpanelFondoLayout);
        jpanelFondoLayout.setHorizontalGroup(
            jpanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelFondoLayout.createSequentialGroup()
                .addComponent(panelMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelFondoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelAddCarri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contadorJuegos)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCarritoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelFondoLayout.createSequentialGroup()
                        .addGroup(jpanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelFondoLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(panelSuperiorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelFondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpanelFondoLayout.setVerticalGroup(
            jpanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelFondoLayout.createSequentialGroup()
                .addComponent(panelMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpanelFondoLayout.createSequentialGroup()
                .addComponent(panelSuperiorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarritoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelFondoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jpanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contadorJuegos)
                            .addComponent(labelAddCarri)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(193, 30));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(193, 30));

        menuHome.setText("Home");
        menuHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuHome.add(jMenuItem7);

        jMenuBar1.add(menuHome);

        menuAddJuegos.setText("  Juegos");
        menuAddJuegos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenuItem4.setText("Añadir Juego");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuAddJuegos.add(jMenuItem4);

        jMenuItem5.setText("Borrar Juego");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuAddJuegos.add(jMenuItem5);

        jMenuItem6.setText("Modificar Juego");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuAddJuegos.add(jMenuItem6);

        jMenuBar1.add(menuAddJuegos);

        menuAddCliente.setText("  Cliente");
        menuAddCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenuItem2.setText("Añadir Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAddCliente.add(jMenuItem2);

        jMenuItem1.setText("Borrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAddCliente.add(jMenuItem1);

        jMenuItem3.setText("Modifcar Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuAddCliente.add(jMenuItem3);

        jMenuBar1.add(menuAddCliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este metodo muestra la lista de clientes al tocar el boton clientes
     *
     * @param evt
     */
    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        ClientesUI listaClientes = new ClientesUI(clientes.obtener());
    }//GEN-LAST:event_btnClientesActionPerformed

    /**
     * Este metodo muestra la lista de clientes al tocar el boton cliente
     *
     * @param evt
     */
    private void btnJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegosActionPerformed
        JuegosUI tablaJuegos = new JuegosUI(juegos.obtener());
    }//GEN-LAST:event_btnJuegosActionPerformed

    /**
     * Este metodo se encarga de mostrar una ventana que permite crear un
     * cliente nuevo
     *
     * @param evt
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CrearClienteUI ventanaCrearCliente = new CrearClienteUI(clientes);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * Este metodo se encarga de mostrar una ventana que permite borrar a los
     * clientes
     *
     * @param evt
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        BorrarClienteUI borrarCliente = new BorrarClienteUI(clientes);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * Este metodo se encarga de mostrar una ventana que permite modificar la
     * informacion de los clientes
     *
     * @param evt
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ModificarClienteUI modificarCliente = new ModificarClienteUI(clientes);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * Este metodo se encarga de mostrar una ventana que permite modificar los
     * juegos
     *
     * @param evt
     */
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ModificarJuegosUI modificarjuegos = new ModificarJuegosUI(juegos);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * Este metodo se encarga de mostrar una ventana que permite crear un juego
     * nuevo
     *
     * @param evt
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CrearJuegosUI crearJuego = new CrearJuegosUI(juegos);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * Este metodo se encarga de mostrar una ventana que permite borrar los
     * juegos
     *
     * @param evt
     */
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        BorrarJuegosUI borrarJuegos = new BorrarJuegosUI(juegos);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void textBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscarActionPerformed

    /**
     * Este metodo se encarga de buscar el juego que se introduce dentro del
     * textField
     *
     * @param evt
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String nombre = this.textBuscar.getText();
        for (Juego j : juegos.obtener()) {
            if (j.getNombre().equalsIgnoreCase(nombre) || j.getDesarrollador().equalsIgnoreCase(nombre) || j.getGenero().equalsIgnoreCase(nombre)) {
                aux = borraretiquetas();
                EtiquetaJuegoUI portada = new EtiquetaJuegoUI(j, juegosParaCliente, juegos, clientes, this);
                panelCentralJuegos.setLayout(new FlowLayout());
                panelCentralJuegos.setOpaque(false);
                panelCentralJuegos.add(portada.getEtiqueta(contadorJuegos));
                panelCentralJuegos.updateUI();
                validarEtiquetas = true;
            } else if (nombre.equals("") && validarEtiquetas) {
                borraretiquetas();
                cargarEtiquetas(aux);
                panelCentralJuegos = aux;
                validarEtiquetas = false;
                panelCentralJuegos.updateUI();
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Este metodo deja en blanco el buscador de texto al darle click
     *
     * @param evt
     */
    private void textBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBuscarMouseClicked
        this.textBuscar.setText("");
    }//GEN-LAST:event_textBuscarMouseClicked

    /**
     * Este metodo habre un carrito dende se fijan los detalles para alquilar
     * los juegos
     *
     * @param evt
     */
    private void btnCarritoTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoTopActionPerformed
        CarritoUI carrito = new CarritoUI(juegosParaCliente, clientes, juegos, this);
    }//GEN-LAST:event_btnCarritoTopActionPerformed

    /**
     * Este metodo se encarga de cerrar la tienda
     *
     * @param evt
     */
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * Este metodo abre una ventana que permite devolver los juegos alquilados
     * por los clientes
     *
     * @param evt
     */
    private void btnDevolverJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverJuegosActionPerformed
        SeleccionarClienteUI seleCliente = new SeleccionarClienteUI(clientes, juegos);

    }//GEN-LAST:event_btnDevolverJuegosActionPerformed

    /**
     * Este metodo se encarga de mostrar el informe de las transacciones de la
     * semana hechas en la tienda
     *
     * @param evt
     */
    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        InformeUI info = new InformeUI(clientes, juegos);
    }//GEN-LAST:event_btnInformesActionPerformed

    /**
     * Este metodo muestra todas la politicas de la tienda
     *
     * @param evt
     */
    private void btnPoliticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliticasActionPerformed
        PoliticasUI politics = new PoliticasUI();
    }//GEN-LAST:event_btnPoliticasActionPerformed

    /**
     * Este metodo se encarga de cargar todas la etiquetas al panel central
     *
     * @param panel
     */
    private void cargarEtiquetas(JPanel panel) {
        panel.setLayout(new GridLayout(2, 4, 0, 0));
        for (Juego j : juegos.obtener()) {
            EtiquetaJuegoUI portada = new EtiquetaJuegoUI(j, juegosParaCliente, juegos, clientes, this);
            this.panelCentralJuegos.add(portada.getEtiqueta(contadorJuegos));
        }
    }

    /**
     * Este metodo se encarga de borrar todas las etiquetas del panel central
     *
     * @return
     */
    private JPanel borraretiquetas() {
        JPanel panelleno = panelCentralJuegos;
        this.panelCentralJuegos.removeAll();
        return panelleno;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ";
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);

            }
        });
    }
    /*
    *Se definen las variables de clase
     */
    private RepoClientes clientes = new RepoClientes("./src/TxtRepositorios/TxTClientes.txt");
    private RepoJuegos juegos = new RepoJuegos("./src/TxtRepositorios/TxTJuegos.txt");
    private int cantJuegos = (juegos.obtener().size() / 2);
    private ArrayList juegosParaCliente = new ArrayList();
    private boolean validarEtiquetas = false;
    private JPanel aux = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCarritoTop;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDevolverJuegos;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnJuegos;
    private javax.swing.JButton btnPoliticas;
    private javax.swing.JLabel contadorJuegos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddCarri;
    private javax.swing.JMenu menuAddCliente;
    private javax.swing.JMenu menuAddJuegos;
    private javax.swing.JMenu menuHome;
    private javax.swing.JPanel panelCentralJuegos;
    private javax.swing.JPanel panelMenuLateral;
    private javax.swing.JPanel panelSuperiorBuscar;
    private javax.swing.JTextField textBuscar;
    // End of variables declaration//GEN-END:variables

}
